name: Test

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  global_fmt:
    name: Fmt project
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Run fmt
        run: |
          OUTPUT="$((gofmt -l . | grep -v '^vendor/') || :)"
          if [ -z "${OUTPUT}" ]
          then
              echo "::set-output name=fmt::ok"
              echo "ok"
          else
              echo "::set-output name=fmt::${OUTPUT}"
              echo "${OUTPUT}"
              exit 1
          fi

  build_project:
    name: Build project
    runs-on: ubuntu-20.04
    needs: [global_fmt]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Build
        run: |
          cd cmd/server
          go build .
